### ISSUE TITLE
Found the source of the RegEx extension

### ISSUE THREAD

**Issue by sylveon** [Bungalow12/UsefulCSharpExt#1]
It's coming from [here](http://stackoverflow.com/questions/2656116/replace-named-group-in-regex-with-value#13342795)

**Comment by ghost** [comment]
Thanks! It's amazing how hard it was for me to try and find that again. I'll add the link.

**Comment by sylveon** [comment]
It was pretty easy: google a part of the code

**Comment by Bungalow12** [comment]
Yeah I should have put more effort into it.
On Sep 20, 2015 11:46 AM, Charles Milette notifications@github.com wrote:It was pretty easy: google a part of the code
